name: Hardhat build, test and coverage

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: npm Install
        run: npm install
      
      - name: Create env File
        run: |
          touch .env
          echo COINMARKETCAP_API_KEY='${{ secrets.COINMARKETCAP_API_KEY }}' >> .env
          echo NFT_NAME="AffeMitWaffe" >> .env
          echo NFT_SYMBOL="AMW" >> .env
          echo INITIAL_BASE_TOKEN_URI="https://something.aws.s3.com/json/" >> .env
          echo COLLECTION_URI="https://something.aws.s3.com/json/collection.json" >> .env

      - name: Run Hardhat Tests
        run: npx hardhat test

      - name: Check Coverage
        run: npx hardhat coverage
